apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: caesaryty/account-service:746682c53608e94a0bc4659974ae6df6f6bc932e
        ports:
        - containerPort: 8080
